version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  install:
    commands:
      - n 16.14.0
  build:
    commands:
      - npm run build-prod

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: /dist/painting-store
